name: release

on:
  push:
    branches:
      - main
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install build dependencies
      run: ./helper.sh reqs
    - name: install requirements
      run: pip install -r requirements.txt
    - name: code check
      run: ./helper.sh code_check
    - name: run tests
      run: ./helper.sh test
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: get timestamp
      id: timestamp
      run: echo "::set-output name=ts::$(date +'%y%m%d%H%M%S')"
    - name: install build dependencies
      run: ./helper.sh reqs
    - name: build package
      run: ./helper.sh build
    - name: publish package to pypi
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
